---
repository:
  name: libvirt-prometheus-exporter
  description: 📊prometheus exporter for libvirt written in python
  topics: libvirt-exporter, libvirt-prometheus-exporter, prometheus-exporter, prometheus, libvirt, libvirtd

  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false

  default_branch: master

  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true

labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  - name: duplicate
    color: cfd3d7
    description: This issue or pull request already exists
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: good first issue
    color: 7057ff
    description: Good for newcomers
  - name: help wanted
    color: 008672
    description: Extra attention is needed
  - name: invalid
    color: e4e669
    description: This doesn't seem right
  - name: question
    color: d876e3
    description: Further information is requested
  - name: wontfix
    color: ffffff
    description: This will not be worked on
  - name: dependencies
    color: 0366d6
    description: Pull requests that update a dependency file
  - name: security
    description: Security relevant changes
    color: efc04a
  - name: removed
    description: Functionality that has been removed
    color: e0b862
  - name: deprecation
    description: Functionality that has been deprecated
    color: f9f99d
  - name: changed
    description: Functionality that has been changed
    color: 3ed678
  - name: semver:patch
    color: 834dd1
    description: Change leading to a patch level version bump
  - name: semver:minor
    color: 764ab5
    description: Change leading to a minor level version bump
  - name: semver:major
    color: 6b3bad
    description: A (breaking) change leading to a major version bump

...